(function() {var implementors = {};
implementors["lightbeam"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"lightbeam/enum.ExecutionError.html\" title=\"enum lightbeam::ExecutionError\">ExecutionError</a>","synthetic":false,"types":["lightbeam::module::ExecutionError"]}];
implementors["wasmtime"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"struct\" href=\"wasmtime/struct.Trap.html\" title=\"struct wasmtime::Trap\">Trap</a>","synthetic":false,"types":["wasmtime::trap::Trap"]}];
implementors["wasmtime_environ"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"wasmtime_environ/enum.CompileError.html\" title=\"enum wasmtime_environ::CompileError\">CompileError</a>","synthetic":false,"types":["wasmtime_environ::compilation::CompileError"]}];
implementors["wasmtime_jit"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"wasmtime_jit/enum.ActionError.html\" title=\"enum wasmtime_jit::ActionError\">ActionError</a>","synthetic":false,"types":["wasmtime_jit::action::ActionError"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"struct\" href=\"wasmtime_jit/struct.UnknownInstance.html\" title=\"struct wasmtime_jit::UnknownInstance\">UnknownInstance</a>","synthetic":false,"types":["wasmtime_jit::context::UnknownInstance"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"wasmtime_jit/enum.ContextError.html\" title=\"enum wasmtime_jit::ContextError\">ContextError</a>","synthetic":false,"types":["wasmtime_jit::context::ContextError"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"wasmtime_jit/enum.SetupError.html\" title=\"enum wasmtime_jit::SetupError\">SetupError</a>","synthetic":false,"types":["wasmtime_jit::instantiate::SetupError"]}];
implementors["wasmtime_runtime"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"struct\" href=\"wasmtime_runtime/struct.LinkError.html\" title=\"struct wasmtime_runtime::LinkError\">LinkError</a>","synthetic":false,"types":["wasmtime_runtime::instance::LinkError"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"wasmtime_runtime/enum.InstantiationError.html\" title=\"enum wasmtime_runtime::InstantiationError\">InstantiationError</a>","synthetic":false,"types":["wasmtime_runtime::instance::InstantiationError"]}];
implementors["yanix"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"yanix/enum.Errno.html\" title=\"enum yanix::Errno\">Errno</a>","synthetic":false,"types":["yanix::errno::Errno"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"yanix/enum.YanixError.html\" title=\"enum yanix::YanixError\">YanixError</a>","synthetic":false,"types":["yanix::YanixError"]}];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        })()